-- 2619) Super Luxo --

SELECT
	A.NAME,
	B.NAME,
	A.PRICE
FROM PRODUCTS AS A
LEFT JOIN PROVIDERS AS B
ON A.ID_PROVIDERS = B.ID
LEFT JOIN CATEGORIES AS C
ON A.ID_CATEGORIES = C.ID
WHERE 
	A.PRICE > 1000
	AND UPPER(C.NAME) = ('SUPER LUXURY');
	
	