-- 2620) Pedidos no Primeiro Semestre --

SELECT
	A.NAME,
	B.ID
FROM CUSTOMERS AS A
LEFT JOIN ORDERS AS B
ON A.ID = B.ID_CUSTOMERS
WHERE 
	TO_CHAR(B.ORDERS_DATE, 'YYYY-MM') > '2016-00'
	AND TO_CHAR(B.ORDERS_DATE, 'YYYY-MM') < '2016-07';
	
