 -- 2990) CPF Dos Empregados --
 
SELECT
	A.CPF,
	A.ENOME,
	B.DNOME
FROM EMPREGADOS AS A
INNER JOIN DEPARTAMENTOS AS B
ON A.DNUMERO = B.DNUMERO
WHERE A.CPF NOT IN (SELECT CPF_EMP FROM TRABALHA)
ORDER BY A.CPF;
