-- 2994) Quanto Ganha um Médico? --

SELECT
	A.NAME,
	ROUND(SUM((C.HOURS * 150) + ((C.HOURS * 150) * B.BONUS/100)), 1) AS SALARY
FROM DOCTORS AS A
LEFT JOIN ATTENDANCES AS C
ON A.ID = C.ID_DOCTOR
LEFT JOIN WORK_SHIFTS AS B
ON B.ID = C.ID_WORK_SHIFT
GROUP BY A.NAME
ORDER BY SALARY DESC;
